apiVersion: v1
kind: Pod
metadata:
  name: adapter
spec:
  volumes:
  - name: shared-logs 
    emptyDir: {}
  containers:
  - name: main-container
    image: alpine
    command: ["/bin/sh"]
    args: ["-c", "while true; do date >  /tmp/index.html && top -n 1 -b >>  /tmp/index.html; sleep 10;done"]
    volumeMounts:
    - name: shared-logs
      mountPath: /var/log
  - name: adapter-container
    image: alpine
    command: ["/bin/sh"]
    args: ["-c", "while true; do (cat  /tmp/index.html | head -1 > /tmp/index-output.html) && (cat / /tmp/index.html | head -2 | tail -1 | grep
 -o -E '\\d+\\w' | head -1 >> /tmp/index-output.html) && (cat  /tmp/index.html | head -3 | tail -1 | grep
-o -E '\\d+%' | head -1 >> /tmp/index-output.html); sleep 5; done"]
    volumeMounts:
    - name: shared-logs
      mountPath: /var/log
