apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: weather
  name: weather
spec:
  replicas: 3
  selector:
    matchLabels:
      app: weather
  template:
    metadata:
      labels:
        app: weather
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
      - image: nginx:1.17
        name: weather
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: "100m"
            memory: "512Mi"
# monolith
# scale up / down  kubectl scale --replicas=2 deploy weather
# autoscale  kubectl autoscale --min 2 --max 5 deploy weather   (metrics-server should be running in the cluster)
